# Generated by Django 4.0.3 on 2022-04-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='feedbackform',
            new_name='feedback',
        ),
    ]
